spring:
  datasource:
    url: jdbc:sqlserver://ene.caygszhmpvhv.ap-northeast-2.rds.amazonaws.com;databaseName=ene
    username: admin
    password: 12345678
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace